name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/676826847:latest
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_image
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          timeout: 30m
          command_timeout: 30m
          script: |
            nohup sh -c "
              sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/676826847:latest &&
              if [ \$(sudo docker ps -aq --filter "name=^/flask-test$") ]; then
                sudo docker stop flask-test &&
                sudo docker rm flask-test
              fi &&
              env_file=\"$HOME/.appseed/envs/.env.676826847\" &&
              if [ -f \$env_file ]; then
                sudo docker run -d -p 31727:5000 --name flask-test --network appseed-network --env-file \$env_file ${{ secrets.DOCKERHUB_USERNAME }}/676826847
              else
                sudo docker run -d -p 31727:5000 --name flask-test --network appseed-network ${{ secrets.DOCKERHUB_USERNAME }}/676826847
              fi
              curl -X POST -H 'Content-type: application/json' -d '{\"status\": \"success\", \"app_id\": ${{ secrets.APP_ID }}}' ${{ secrets.CALLBACK_URL }}
            " > ~/.appseed/logs/flask-test.log 2>&1 &